### ISSUE TITLE
How much memory is required for large scale search?

### ISSUE THREAD

**Issue by AlekseyMalyshev** [robertvazan/sourceafis-net#8]
I tested this database with 100,000 records, 10 fingerprint each and it requires 46 Gb of RAM just for the templates. Is this as designed? Previous version of SourceAFIS 1.7 required 5-10 times less memory.

**Comment by robertvazan** [comment]
Estimated RAM footprint per template can be seen here:

https://sourceafis.machinezoo.com/cli

You are observing twice higher RAM consumption either because of GC overhead or because you are benchmarking SourceAFIS on templates with unusually many minutiae (e.g. rolled prints). Try to force GC after templates are loaded.

The algorithm did not change much between 1.7 and 3.x. SourceAFIS 1.7 required comparable amount of RAM. It was just allocating it lazily upon first identification. Version 3.x allocates RAM immediately upon template decoding, so that performance is more predictable.

But yes, RAM footprint could be optimized, which would be especially relevant in mid-sized applications. Small applications don't care. Large applications are limited more by CPU than RAM.

You have a few options:

1. Use dedicated service written in Java to do the matching. Java is not only more memory efficient but also about 2x faster.
2. Load (and match) fewer than 10 fingers per person.
3. Optimize the code or pay me to do the same.

More information about custom development is here:

https://sourceafis.machinezoo.com/custom

**Comment by AlekseyMalyshev** [comment]
> You are observing twice higher RAM consumption either because of GC overhead or because you are benchmarking SourceAFIS on templates with unusually many minutiae (e.g. rolled prints). Try to force GC after templates are loaded.

Yes, we are using rolled prints. One way to optimize was to use `float` instead of double `short` instead of `int` in `EdgeShape`, which seems to be taking most of the RAM space. Also this could be converted to struct to minimize GC overhead.

**Comment by robertvazan** [comment]
@AlekseyMalyshev Would you mind making a PR for this?

**Comment by AlekseyMalyshev** [comment]
> @AlekseyMalyshev Would you mind making a PR for this?

This will not significantly improve the situation. According to my tests, the new AFIS version requires 30 times more memory compared to the previous one. Even if we manage to half the size, it will still be 15 times more than the previous version.

**Comment by robertvazan** [comment]
@AlekseyMalyshev 30x? That's impossible. Try to measure memory consumption in SourceAFIS 1.7 after running one identification over all fingerprints. That will force initialization of `MatcherCache` field in SourceAFIS 1.7 templates.

**Comment by AlekseyMalyshev** [comment]
Yes, you are right, but the memory footprint is much smaller on SourceAFIS 1.7. It is clear from comparing the structures:

```
    public struct EdgeShape
    {
        public short Length;
        public byte ReferenceAngle;
        public byte NeighborAngle;
    }
```
And here is the new version:
```
        public readonly int Length;
        public readonly double ReferenceAngle;
        public readonly double NeighborAngle;
```
This is nearly eight times smaller since double is 8 bytes in 64 bit .NET. So we need to change double to byte and int to short. The latter should be OK, but I am not sure about the angles. This will be a significant rework that might decrease performance.

**Comment by robertvazan** [comment]
Reducing `double` to `float` is simple and it does large part of the job. Integer angles can be done in another round. Ditto for replacing inheritance with composition in order to switch from reference type to value type.

**Comment by AlekseyMalyshev** [comment]
I'll see what I can do.

**Comment by McFads1** [comment]
was this ever addressed? @robertvazan @AlekseyMalyshev 

I planned on using this library on a large scale search, but at 46gb ram for 100k users that wouldn't be feasable

**Comment by AlekseyMalyshev** [comment]
@McFads1 No. I found that the previous version requires less memory and the new one does not offer much benefits.

**Comment by McFads1** [comment]
Appreciate the response @AlekseyMalyshev . I'll clone 1.7 then. Much appreciated!

**Comment by robertvazan** [comment]
New version reduces RAM footprint from 20KB to 5KB per template. Further improvements are possible, especially w.r.t integer angles, but that's a wholly different issue with significant impact on the algorithm.
